EComWeb/Controllers/UserRolesController.cs
using ECom.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EComWeb.Controllers;

[Authorize(Roles = "Admin")]
public class UserRolesController : Controller
{
    private readonly SignInManager<ApplicationUser> _signInManager;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly RoleManager<ApplicationRole> _roleManager;

    public UserRolesController(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager,
        RoleManager<ApplicationRole> roleManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _roleManager = roleManager;
    }
    // GET
    public async Task<IActionResult> Index(int userId)
    {
        var viewModel = new UserRolesViewMode();
        viewModel.RoleNames = new List<string>();
        var user = await _userManager.FindByIdAsync(userId.ToString());
        viewModel.UserId = userId;
        viewModel.Username = user.UserName;
        var roleOfUser = await _userManager.GetRolesAsync(user);
        for (int i = 0; i < _roleManager.Roles.Count(); i++)
        {
            viewModel.RoleNames.Add(_roleManager.Roles.ToList()[i].Name);
            if (roleOfUser[0] == viewModel.RoleNames[i]) viewModel.SelectedRole = i;
        }
        return View(viewModel);
    }
    //POST
    [ValidateAntiForgeryToken]
    [HttpPost]
    public async Task<IActionResult> Index(UserRolesViewMode viewMode)
    {
        if (!ModelState.IsValid) return BadRequest();
        var user = await _userManager.FindByIdAsync(viewMode.UserId.ToString());
        for (int i = 0; i < viewMode.RoleNames.Count; i++)
        {
            if (viewMode.SelectedRole == i) await _userManager.AddToRoleAsync(user, viewMode.RoleNames[i]);
            else await _userManager.RemoveFromRoleAsync(user, viewMode.RoleNames[i]);
        }
        return RedirectToAction("Index","User");
    }
}

EComWeb/Views/UserRoles/Index.cshtml
@model ECom.Models.UserRolesViewMode

@{
    ViewData["Title"] = "User Roles Manager for User " + @Model.Username;
    Layout = "_Layout";
}

<h1>@ViewData["Title"]</h1>
<div class="card">
    <div id="viewAll" class="card-body table-responsive">
        <form asp-controller="UserRoles" method="post" asp-action="Index" asp-route-id="@Model.UserId" class="d-inline">
            <input asp-for="@Model.UserId" type="hidden" />
            <input asp-for="@Model.Username" type="hidden"/>
            <table class="table table-striped" id="userRolesTable">
                <thead>
                    <tr>
                        <th>
                            Role
                        </th>
                        <th>
                            Status
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.RoleNames.Count; i++)
                    {
                        <tr>
                            <td>
                                <input asp-for="@Model.RoleNames[i]" type="hidden" />
                                @Model.RoleNames[i]
                            </td>
                            <td>
                                <div class="form-check m-1">
                                    <input type="radio" asp-for="@Model.SelectedRole" value="@i" class="form-check-input" />
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="col-sm-12" style=" padding: 20px 20px 0px 0px">
                <button type="submit" id="save" class="btn bg-primary">
                    <i class="fa fa-check"></i>
                    Save
                </button>
            </div>
        </form>
    </div>
</div>